# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WDDjPeSUp6NeoiLekMGTi3eAZWOZ26E1
"""

import pandas as pd

df_pge_service = pd.read_excel('2_Electricity Rate Plan.xlsx', sheet_name='PG&E Service Area')
cca_df = pd.read_excel('2_Electricity Rate Plan.xlsx', sheet_name='CCA')
jrp_plans_df = pd.read_excel('2_Electricity Rate Plan.xlsx', sheet_name='Joint Rate Plan')
bundled_df = pd.read_excel('2_Electricity Rate Plan.xlsx', sheet_name='Bundled Peak Time Price')
unbundled_df = pd.read_excel('2_Electricity Rate Plan.xlsx', sheet_name='Unbundled Peak Time Price')

def check_pge_service_area(zip_code):
    result = df_pge_service[df_pge_service['PG&E Service area Zip Code'] == zip_code]
    if result.empty:
        return None
    return result.iloc[0]

def check_cca(zip_code):
  cca_column=[]
  for column in cca_df.columns:
    if zip_code in cca_df[column].values:
      cca_column.append(column)
  if not cca_column:
      return None
  return cca_column

def match_plan(cca_area):
  possible_plans=[]
  for area in cca_area:
   match=jrp_plans_df.loc[jrp_plans_df['Location']==area,['Plan']]
   possible_plans.append(match)
  return possible_plans


def cca_sector(sector, plans):
    sector_plans = []
    for plan in jrp_plans_df.itertuples():
        if plan.Sector == sector:
            sector_plans.append(plan.Plan)
    return sector_plans

def bundled(bundle,sector):
  bundle_plans=[]
  for plan in bundled_df.itertuples():
    if plan.Sector==sector:
      bundle_plans.append(plan.Plan)
  return bundle_plans

def unbundled(bundle,sector):
  unbundle_plans=[]
  for plan in unbundled_df.itertuples():
    if plan.Sector==sector:
      unbundle_plans.append(plan.Plan)
  return unbundle_plans

#User input zip code
zip_code = int(input("Enter the zip code: "))
pge_area =check_pge_service_area(zip_code)
cca_area=check_cca(zip_code)
if pge_area is not None:
  print("The zip code is PG&E Service Area")
else:
  print("The zip code is not in the service area")
print(cca_area)
if cca_area is None:
  print("The Zip code is only a PG&E Service Area")
  bundle=input("Enter if bundle or unbundle")
  sector=input("Enter the sector")
  if bundle=="bundle":
   plan_names=bundled(bundle,sector)
   print(plan_names)
  elif bundle=="unbundle":
   plan_names=unbundled(bundle,sector)
   print(plan_names)
  else:
    print("Enter valid input")

else:
  plans=match_plan(cca_area)
  plan_names = []
  for df in plans:
      plan_names.extend(df['Plan'].tolist())
  print(plan_names)

  sector=input("Enter your sector")
  result=cca_sector(sector,plan_names)
  print(result)

  final_plans=list(set(result) & set(plan_names))
  print("Comman Plans are",",".join(final_plans))
